begin
   for r in (select table_name from user_tables) loop
      execute immediate 'drop table ' || r.table_name || ' cascade constraints';
   end loop;
end;
/


create table angajati (
    id_angajat      number generated by default as identity primary key,
    nume            varchar2(100),
    prenume         varchar2(100),
    functie         varchar2(100),
    cod_cor         varchar2(20),
    salariu_brut    number(10,2) check (salariu_brut > 0)
);

create table echipamente (
    id_echipament   number generated by default as identity primary key,
    denumire        varchar2(200),
    valoare_init    number(10,2) check (valoare_init >= 0),
    durata_ani      number(2)
);

create table furnizori (
    id_furnizor     number generated by default as identity primary key,
    nume_firma      varchar2(200),
    contact_info    varchar2(200)
);

create table categorii (
    id_categorie    number generated by default as identity primary key,
    nume_categorie  varchar2(100)
);

create table clienti (
    id_client       number generated by default as identity primary key,
    nume_prenume    varchar2(200),
    email           varchar2(100) unique,
    telefon         varchar2(20)
);

create table materii_prime (
    id_materie      number generated by default as identity primary key,
    id_furnizor     number references furnizori(id_furnizor),
    tip_material    varchar2(100),
    stoc_grame_buc  number(12,3) default 0,
    pret_unitar     number(10,2) check (pret_unitar > 0)
);

create table produse (
    id_produs       number generated by default as identity primary key,
    id_categorie    number references categorii(id_categorie),
    nume_bijuterie  varchar2(200),
    pret_vanzare    number(10,2) check (pret_vanzare > 0),
    pret_manopera   number(10,2) default 0
);

create table comenzi (
    id_comanda      number generated by default as identity primary key,
    id_client       number references clienti(id_client),
    id_vanzator     number references angajati(id_angajat),
    data_comanda    date default sysdate,
    valoare_totala  number(15,2)
);


create table compozitie_produse (
    id_compozitie   number generated by default as identity primary key,
    id_produs       number references produse(id_produs) on delete cascade,
    id_materie      number references materii_prime(id_materie),
    cantitate_necesara number(10,3) check (cantitate_necesara > 0)
);

create table detalii_comenzi (
    id_detaliu      number generated by default as identity primary key,
    id_comanda      number references comenzi(id_comanda) on delete cascade,
    id_produs       number references produse(id_produs),
    cantitate       number default 1
);

create table servicii_restaurare (
    id_service      number generated by default as identity primary key,
    id_client       number references clienti(id_client),
    id_bijutier     number references angajati(id_angajat),
    id_echipament   number references echipamente(id_echipament),
    descriere_lucru varchar2(500),
    cost_service    number(10,2) check (cost_service >= 0)
);

commit;





insert into angajati (nume, prenume, functie, cod_cor, salariu_brut) 
values ('petcu', 'david eugen', 'administrator', '242111', 12000); 

insert into angajati (nume, prenume, functie, cod_cor, salariu_brut) 
values ('pais', 'dorian alexandru', 'sef atelier', '121902', 7500); 

insert into angajati (nume, prenume, functie, cod_cor, salariu_brut) 
values ('petre', 'andrei ionut', 'bijutier', '731301', 8000); 

insert into angajati (nume, prenume, functie, cod_cor, salariu_brut) 
values ('popa', 'cristian', 'designer produse', '216304', 6500);

insert into angajati (nume, prenume, functie, cod_cor, salariu_brut) 
values ('vasilescu', 'ana', 'director vanzari', '122107', 7000); 

insert into angajati (nume, prenume, functie, cod_cor, salariu_brut) 
values ('ionescu', 'mihai', 'agent vanzari', '332203', 5500); 

insert into angajati (nume, prenume, functie, cod_cor, salariu_brut) 
values ('georgescu', 'elena', 'responsabil economic', '263102', 5000); 


insert into echipamente (denumire, valoare_init, durata_ani) 
values ('echipament gravura laser', 30000, 5); 

insert into echipamente (denumire, valoare_init, durata_ani) 
values ('echipament turnare si topire', 25000, 7);

insert into echipamente (denumire, valoare_init, durata_ani) 
values ('echipament slefuire si lustruire', 15000, 5); 

insert into echipamente (denumire, valoare_init, durata_ani) 
values ('sistem securitate si alarma', 5000, 5);

insert into echipamente (denumire, valoare_init, durata_ani) 
values ('echipament it designer', 8000, 3); 


insert into furnizori (nume_firma, contact_info) 
values ('metal-lux romania', 'office@metallux.ro');

insert into materii_prime (id_furnizor, tip_material, stoc_grame_buc, pret_unitar) 
values (1, 'aur 18k galben', 250, 320);

insert into materii_prime (id_furnizor, tip_material, stoc_grame_buc, pret_unitar) 
values (1, 'argint 925', 1000, 4.5); 


insert into categorii (nume_categorie) values ('inele'); 
insert into categorii (nume_categorie) values ('bratari'); 
insert into categorii (nume_categorie) values ('seturi mireasa'); 

insert into produse (id_categorie, nume_bijuterie, pret_vanzare, pret_manopera) 
values (1, 'inel argint cu pietre', 450, 150); 

insert into produse (id_categorie, nume_bijuterie, pret_vanzare, pret_manopera) 
values (2, 'bratara aur personalizata', 3500, 800); 

insert into produse (id_categorie, nume_bijuterie, pret_vanzare, pret_manopera) 
values (3, 'set mireasa "eternity"', 8500, 2000); 


insert into compozitie_produse (id_produs, id_materie, cantitate_necesara) values (1, 2, 10);


insert into compozitie_produse (id_produs, id_materie, cantitate_necesara) values (2, 1, 8);


insert into clienti (nume_prenume, email, telefon) 
values ('marina andreea', 'andreea@email.com', '0722000111');

insert into comenzi (id_client, id_vanzator, valoare_totala) 
values (1, 6, 3500);

insert into detalii_comenzi (id_comanda, id_produs, cantitate) 
values (1, 2, 1);


insert into servicii_restaurare (id_client, id_bijutier, id_echipament, descriere_lucru, cost_service) 
values (1, 3, 1, 'gravura laser mesaj personalizat bratara', 200);

commit;








--index
create index idx_comenzi_data on comenzi(data_comanda);
create index idx_produse_nume on produse(nume_bijuterie);


--profitability analysis
create or replace view v_profit_bijuterii as
select 
    p.nume_bijuterie,
    p.pret_vanzare,
    p.pret_manopera,
    sum(cp.cantitate_necesara * mp.pret_unitar) as cost_materie_prima,
    (p.pret_vanzare - p.pret_manopera - sum(cp.cantitate_necesara * mp.pret_unitar)) as profit_net_unitate
from produse p
join compozitie_produse cp on p.id_produs = cp.id_produs
join materii_prime mp on cp.id_materie = mp.id_materie
group by p.nume_bijuterie, p.pret_vanzare, p.pret_manopera;

--price update
update produse 
set pret_vanzare = 7500 
where nume_bijuterie = 'bratara aur personalizata';

commit;



--top seller
select 
    a.nume || ' ' || a.prenume as vanzator,
    count(c.id_comanda) as numar_comenzi,
    sum(c.valoare_totala) as total_incasari
from angajati a
join comenzi c on a.id_angajat = c.id_vanzator
group by a.nume, a.prenume
order by total_incasari desc;



--price advisor
select 
    p.nume_bijuterie,
    (p.pret_manopera + sum(cp.cantitate_necesara * mp.pret_unitar)) as cost_total_productie,
    p.pret_vanzare as pret_actual,
    round((p.pret_manopera + sum(cp.cantitate_necesara * mp.pret_unitar)) * 1.3, 2) as pret_recomandat_lux,
    case 
        when p.pret_vanzare < (p.pret_manopera + sum(cp.cantitate_necesara * mp.pret_unitar)) then 'ALERTA: PIERDERE'
        else 'PROFITABIL'
    end as status_business
from produse p
join compozitie_produse cp on p.id_produs = cp.id_produs
join materii_prime mp on cp.id_materie = mp.id_materie
group by p.nume_bijuterie, p.pret_vanzare, p.pret_manopera
order by cost_total_productie desc;




--supply chain
create or replace view v_alerta_aprovizionare as
select 
    mp.tip_material,
    mp.stoc_grame_buc as stoc_actual,
    case 
        when mp.stoc_grame_buc < 50 then 'REAPROVIZIONARE URGENTA'
        when mp.stoc_grame_buc < 150 then 'STOC LIMITAT'
        else 'STOC OPTIM'
    end as status_material
from materii_prime mp;



--return on investment
select 
    e.denumire as utilaj,
    e.valoare_init as investitie_initiala,
    count(sr.id_service) as numar_utilizari,
    sum(sr.cost_service) as venituri_generate,
    round((sum(sr.cost_service) / e.valoare_init) * 100, 2) as procent_recuperare_investitie
from echipamente e
left join servicii_restaurare sr on e.id_echipament = sr.id_echipament
group by e.denumire, e.valoare_init
order by venituri_generate desc;


--trigger
create table istoric_preturi (
    id_istoric     number generated by default as identity primary key,
    id_produs      number,
    pret_vechi     number,
    pret_nou       number,
    data_modificare date default sysdate
);

create or replace trigger trg_audit_pret
after update of pret_vanzare on produse
for each row
begin
    insert into istoric_preturi (id_produs, pret_vechi, pret_nou)
    values (:old.id_produs, :old.pret_vanzare, :new.pret_vanzare);
end;
/

--activate trigger
update produse set pret_vanzare = 3800 where nume_bijuterie = 'bratara aur personalizata';
commit;

select * from v_profit_bijuterii where profit_net_unitate > 100;
select * from v_alerta_aprovizionare;

